// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoazmmeajjfifamsrnab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYXptbWVhampmaWZhbXNybmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTUzNzIsImV4cCI6MjA2ODQ3MTM3Mn0.kwF_mIv-Y1bz3zGydmmsqXGdT0BLqZXX-iTqWOoGReo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});